set $pan_backend http://host.docker.internal:11946;
set $apppan_backend http://host.docker.internal:11946;
set $pan_assets_backend http://host.docker.internal:11946;
set $apppan_assets_backend http://host.docker.internal:11946;
